// Generated by gencpp from file pose_est_new/CameraState.msg
// DO NOT EDIT!


#ifndef POSE_EST_NEW_MESSAGE_CAMERASTATE_H
#define POSE_EST_NEW_MESSAGE_CAMERASTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pose_est_new
{
template <class ContainerAllocator>
struct CameraState_
{
  typedef CameraState_<ContainerAllocator> Type;

  CameraState_()
    : header()
    , q0(0.0)
    , q1(0.0)
    , q2(0.0)
    , q3(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  CameraState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , q0(0.0)
    , q1(0.0)
    , q2(0.0)
    , q3(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _q0_type;
  _q0_type q0;

   typedef double _q1_type;
  _q1_type q1;

   typedef double _q2_type;
  _q2_type q2;

   typedef double _q3_type;
  _q3_type q3;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::pose_est_new::CameraState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_est_new::CameraState_<ContainerAllocator> const> ConstPtr;

}; // struct CameraState_

typedef ::pose_est_new::CameraState_<std::allocator<void> > CameraState;

typedef boost::shared_ptr< ::pose_est_new::CameraState > CameraStatePtr;
typedef boost::shared_ptr< ::pose_est_new::CameraState const> CameraStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_est_new::CameraState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_est_new::CameraState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pose_est_new

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pose_est_new': ['/home/tg/slam_mono/src/pose_est_new/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pose_est_new::CameraState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_est_new::CameraState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_est_new::CameraState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_est_new::CameraState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_est_new::CameraState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_est_new::CameraState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_est_new::CameraState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a361b93d4d02dcf08b79ee6893f8b6b2";
  }

  static const char* value(const ::pose_est_new::CameraState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa361b93d4d02dcf0ULL;
  static const uint64_t static_value2 = 0x8b79ee6893f8b6b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_est_new::CameraState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_est_new/CameraState";
  }

  static const char* value(const ::pose_est_new::CameraState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_est_new::CameraState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float64 q0\n\
float64 q1\n\
float64 q2\n\
float64 q3\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pose_est_new::CameraState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_est_new::CameraState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.q0);
      stream.next(m.q1);
      stream.next(m.q2);
      stream.next(m.q3);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_est_new::CameraState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_est_new::CameraState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "q0: ";
    Printer<double>::stream(s, indent + "  ", v.q0);
    s << indent << "q1: ";
    Printer<double>::stream(s, indent + "  ", v.q1);
    s << indent << "q2: ";
    Printer<double>::stream(s, indent + "  ", v.q2);
    s << indent << "q3: ";
    Printer<double>::stream(s, indent + "  ", v.q3);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_EST_NEW_MESSAGE_CAMERASTATE_H
