// Generated by gencpp from file pose_est_new/DataCollectionForSim.msg
// DO NOT EDIT!


#ifndef POSE_EST_NEW_MESSAGE_DATACOLLECTIONFORSIM_H
#define POSE_EST_NEW_MESSAGE_DATACOLLECTIONFORSIM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace pose_est_new
{
template <class ContainerAllocator>
struct DataCollectionForSim_
{
  typedef DataCollectionForSim_<ContainerAllocator> Type;

  DataCollectionForSim_()
    : header()
    , updateCameraState(0)
    , orientation_cam()
    , pos_cam()
    , angular_velocity_imu()
    , linear_acceleration_imu()  {
    }
  DataCollectionForSim_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , updateCameraState(0)
    , orientation_cam(_alloc)
    , pos_cam(_alloc)
    , angular_velocity_imu(_alloc)
    , linear_acceleration_imu(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _updateCameraState_type;
  _updateCameraState_type updateCameraState;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_cam_type;
  _orientation_cam_type orientation_cam;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _pos_cam_type;
  _pos_cam_type pos_cam;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_velocity_imu_type;
  _angular_velocity_imu_type angular_velocity_imu;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_imu_type;
  _linear_acceleration_imu_type linear_acceleration_imu;





  typedef boost::shared_ptr< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> const> ConstPtr;

}; // struct DataCollectionForSim_

typedef ::pose_est_new::DataCollectionForSim_<std::allocator<void> > DataCollectionForSim;

typedef boost::shared_ptr< ::pose_est_new::DataCollectionForSim > DataCollectionForSimPtr;
typedef boost::shared_ptr< ::pose_est_new::DataCollectionForSim const> DataCollectionForSimConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_est_new::DataCollectionForSim_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pose_est_new

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pose_est_new': ['/home/sfox/slam_mono/src/pose_est_new/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef7c30dc1047a86e342d27ddf8805527";
  }

  static const char* value(const ::pose_est_new::DataCollectionForSim_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef7c30dc1047a86eULL;
  static const uint64_t static_value2 = 0x342d27ddf8805527ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_est_new/DataCollectionForSim";
  }

  static const char* value(const ::pose_est_new::DataCollectionForSim_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
int32 updateCameraState\n\
geometry_msgs/Quaternion orientation_cam\n\
geometry_msgs/Vector3 pos_cam\n\
geometry_msgs/Vector3 angular_velocity_imu\n\
geometry_msgs/Vector3 linear_acceleration_imu\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::pose_est_new::DataCollectionForSim_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.updateCameraState);
      stream.next(m.orientation_cam);
      stream.next(m.pos_cam);
      stream.next(m.angular_velocity_imu);
      stream.next(m.linear_acceleration_imu);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataCollectionForSim_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_est_new::DataCollectionForSim_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_est_new::DataCollectionForSim_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "updateCameraState: ";
    Printer<int32_t>::stream(s, indent + "  ", v.updateCameraState);
    s << indent << "orientation_cam: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation_cam);
    s << indent << "pos_cam: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.pos_cam);
    s << indent << "angular_velocity_imu: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity_imu);
    s << indent << "linear_acceleration_imu: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration_imu);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_EST_NEW_MESSAGE_DATACOLLECTIONFORSIM_H
