# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from feature_tracker/FeatureTrackerResult.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FeatureTrackerResult(genpy.Message):
  _md5sum = "d0ed1f072b189a5a0771a879ec6816ba"
  _type = "feature_tracker/FeatureTrackerResult"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 id
int64 cnt
int64 seq
float64 u0
float64 v0
float64 u1
float64 v1"""
  __slots__ = ['id','cnt','seq','u0','v0','u1','v1']
  _slot_types = ['int64','int64','int64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,cnt,seq,u0,v0,u1,v1

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FeatureTrackerResult, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.cnt is None:
        self.cnt = 0
      if self.seq is None:
        self.seq = 0
      if self.u0 is None:
        self.u0 = 0.
      if self.v0 is None:
        self.v0 = 0.
      if self.u1 is None:
        self.u1 = 0.
      if self.v1 is None:
        self.v1 = 0.
    else:
      self.id = 0
      self.cnt = 0
      self.seq = 0
      self.u0 = 0.
      self.v0 = 0.
      self.u1 = 0.
      self.v1 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3q4d().pack(_x.id, _x.cnt, _x.seq, _x.u0, _x.v0, _x.u1, _x.v1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.id, _x.cnt, _x.seq, _x.u0, _x.v0, _x.u1, _x.v1,) = _get_struct_3q4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3q4d().pack(_x.id, _x.cnt, _x.seq, _x.u0, _x.v0, _x.u1, _x.v1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.id, _x.cnt, _x.seq, _x.u0, _x.v0, _x.u1, _x.v1,) = _get_struct_3q4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3q4d = None
def _get_struct_3q4d():
    global _struct_3q4d
    if _struct_3q4d is None:
        _struct_3q4d = struct.Struct("<3q4d")
    return _struct_3q4d
